### ISSUE TITLE
Norwegian DVB-T channels wanted

### ISSUE THREAD

**Issue by robinsmidsrod** [oe-alliance/AutoBouquetsMaker#113] opened 2019-07-07 10:17 UTC
Hi everyone!

I tried using AutoBouquetsMaker on OpenATV 6.2 on a Dreambox DM7020HD, and ended up being blocked because there wasn't any option to find Norwegian channels distributed over DVB-T. I couldn't actually find any Norwegian providers at all in the configuration (not even for DVB-S2 or DVB-C).

What must be done to get those supported? Is there anything I can do to help things along?

**Comment by AbuBaniaz** [comment] 2019-07-09 18:33
They have not been requested, so not added yet.

Have you tried installing and using the Terrestrialscan plugin? If that creates the bouquet in same as official order it will be relatively straight forward.

You may need raw stream recordings from some of your frequencies. Details here
https://github.com/oe-alliance/AutoBouquetsMaker/tree/tools/scripts%20and%20tools

**Comment by robinsmidsrod** [comment] 2019-07-10 09:33
@AbuBaniaz Where can I find the Terrestrialscan plugin? Is it supposed to be in the OpenATV extension list on my tuner, or do I need to look somewhere else?

**Comment by robinsmidsrod** [comment] 2019-07-10 21:41
@AbuBaniaz If you mean a normal automatic scan with DVB-T, I've done that and all of the channels available do show up, but not in the order they're shown on the provider's homepage. The provider is rikstv.no. The channel layout is here: https://www.rikstv.no/produkter/kanalliste/

**Comment by AbuBaniaz** [comment] 2019-07-10 22:01
There is a plugin called Terrestrial scan.  Please use it and report back

**Comment by AbuBaniaz** [comment] 2019-07-10 22:04
It will be under system plugins in order for you to install it. Once installed, it's in menu with tuning/scanning items

**Comment by AbuBaniaz** [comment] 2019-07-12 11:42
screenshot if you need it
![terrestrialscan](https://user-images.githubusercontent.com/6644489/61125740-88e6e000-a4a2-11e9-9288-32f4cdf72e85.jpg)

**Comment by robinsmidsrod** [comment] 2019-07-19 11:13
@AbuBaniaz I've installed the terrestrialscan plugin and performed a scan. It detected 152 channels. Which file do you need from my installation to figure out the next step? I noticed an XML file was generated/updated. Where is it located?

**Comment by Huevos** [comment] 2019-07-20 09:06
When you used TerrestrialScan did it create a bouquet? Was the bouquet in the correct order?

**Comment by robinsmidsrod** [comment] 2019-07-20 20:26
@Huevos Yes, it created a bouquet called "Last Scanned" which contained all of the channels (with the same channels listed multiple times, probably different DVB-T towers, I know I can receive at least two different ones), but not in the order listed on rikstv.no. It also stated that it create an XML file called terrestrial.xml, but it didn't mention where it was saved.

**Comment by AbuBaniaz** [comment] 2019-07-20 22:12
There should have been a terrestrial bouquet too. Please double check.

The terrestrial.xml file will have been created in /etc/enigma2 (it says this in the description text).
Can you attach it as well as your lamedb file which is in the same location.

Also, what frequency is NRK1 for you?

**Comment by robinsmidsrod** [comment] 2019-07-20 22:59
There is no terrestrial bouquet. I even checked with the bouquetEditor in the web interface. I only have one called Favorites (TV) and one called Favorites (Radio).

For some reason there wasn't any terrestrial.xml file in /etc/enigma2, it was straight in /etc. I've attached it below.

[terrestrial-xml.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/3414042/terrestrial-xml.txt)

I had both lamedb and lamedb5 in /etc/enigma2, so I gave you both.

[lamedb.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/3414046/lamedb.txt)
[lamedb5.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/3414045/lamedb5.txt)

NRK1 is at frequency 562MHz. I've attached some screenshots with the service info.

![NRK1_Service](https://user-images.githubusercontent.com/92816/61585011-6e6fcf00-ab52-11e9-88d2-fda42eeaec55.jpg)
![NRK1_PIDs](https://user-images.githubusercontent.com/92816/61585009-6e6fcf00-ab52-11e9-8bc9-d3a26aa3216c.jpg)
![NRK1_Tuner_status](https://user-images.githubusercontent.com/92816/61585010-6e6fcf00-ab52-11e9-9469-a973048f2e8b.jpg)

**Comment by Huevos** [comment] 2019-07-21 20:52
That xml file is nothing to do with this plugin. You need to enable bouquet creation and xml file creation in the plugin config screen.

![ts](https://user-images.githubusercontent.com/2067864/61589186-c6382580-aba6-11e9-9463-40b124c79d0b.jpg)

If a bouquet is not created, that means there are no LCNs in the standard DVB location.

Please use the DVB Stream recorder and make stream recordings of all transport streams that are active in your area. About 30-40 seconds of each transport stream should be sufficient.

Tool to make the recordings is here:
https://github.com/oe-alliance/AutoBouquetsMaker/tree/tools/scripts%20and%20tools/Stream%20recording

What receiver is it.

**Comment by AbuBaniaz** [comment] 2019-07-21 23:55
>What receiver is it?

Dreambox DM7020HD

**Comment by AbuBaniaz** [comment] 2019-07-21 23:59
The terrestrial.xml file you uploaded is the stock file. Please follow Huevos' instructions on running the plugin.

Anyway, for reference purposes the frequencies I got from your lamedb file are as follows
```
<?xml version="1.0" encoding="UTF-8"?>
<locations>
	<terrestrial name="REGION NAME HERE (Europe DVB-T/T2)" flags="5">
		<transponder centre_frequency="474001000" bandwidth="0" constellation="3" code_rate_hp="0" code_rate_lp="0" guard_interval="4" transmission_mode="2" hierarchy_information="4" inversion="2" />
		<transponder centre_frequency="498001000" bandwidth="0" constellation="3" code_rate_hp="0" code_rate_lp="0" guard_interval="4" transmission_mode="2" hierarchy_information="4" inversion="2" />
		<transponder centre_frequency="562001125" bandwidth="0" constellation="3" code_rate_hp="0" code_rate_lp="0" guard_interval="4" transmission_mode="2" hierarchy_information="4" inversion="2" />
		<transponder centre_frequency="578001125" bandwidth="0" constellation="3" code_rate_hp="0" code_rate_lp="0" guard_interval="4" transmission_mode="2" hierarchy_information="4" inversion="2" />
		<transponder centre_frequency="610001250" bandwidth="0" constellation="3" code_rate_hp="0" code_rate_lp="0" guard_interval="4" transmission_mode="2" hierarchy_information="4" inversion="2" />
		<transponder centre_frequency="642001250" bandwidth="0" constellation="3" code_rate_hp="0" code_rate_lp="0" guard_interval="4" transmission_mode="2" hierarchy_information="4" inversion="2" />
		<transponder centre_frequency="658001375" bandwidth="0" constellation="3" code_rate_hp="0" code_rate_lp="0" guard_interval="4" transmission_mode="2" hierarchy_information="4" inversion="2" />
		<transponder centre_frequency="666001375" bandwidth="0" constellation="3" code_rate_hp="0" code_rate_lp="0" guard_interval="4" transmission_mode="2" hierarchy_information="4" inversion="2" />
		<transponder centre_frequency="714001375" bandwidth="0" constellation="3" code_rate_hp="0" code_rate_lp="0" guard_interval="4" transmission_mode="2" hierarchy_information="4" inversion="2" />
		<transponder centre_frequency="738001500" bandwidth="0" constellation="3" code_rate_hp="0" code_rate_lp="0" guard_interval="4" transmission_mode="2" hierarchy_information="4" inversion="2" />
		<transponder centre_frequency="778001500" bandwidth="0" constellation="3" code_rate_hp="0" code_rate_lp="0" guard_interval="4" transmission_mode="2" hierarchy_information="4" inversion="2" />
		<transponder centre_frequency="786001625" bandwidth="0" constellation="3" code_rate_hp="0" code_rate_lp="0" guard_interval="4" transmission_mode="2" hierarchy_information="4" inversion="2" />
	</terrestrial>
</locations>


```

**Comment by robinsmidsrod** [comment] 2019-07-22 16:04
Here is the terrestrial.xml file from the TerrestrialScan plugin.

[terrestrial.xml.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/3418240/terrestrial.xml.txt)

When I was previously trying to run it I got a "Cannot get the NIM" error because I was currently streaming from the receiver.

This was with the following settings:

Tuner: Automatic
Band: UHF/VHF Europe
Clear before scan: Yes
Only free scan: No
Restrict search to single ONID: No
Create terrestrial bouquet: Yes
Create terrestrial xml file: Yes

No bouquet was created. Not sure why.

**Comment by robinsmidsrod** [comment] 2019-07-22 16:13
> If a bouquet is not created, that means there are no LCNs in the standard DVB location.

What is the definition of "LCN"?

> Please use the DVB Stream recorder and make stream recordings of all transport streams that are active in your area. About 30-40 seconds of each transport stream should be sufficient.

What do you mean by "each transport stream"? Does that mean each of the 11 frequencies in the terrestrial.xml file, or each and every found channel?

**Comment by Huevos** [comment] 2019-07-22 17:03
LCN = Logical Channel Numbers. This is what we are looking for. If present this is used to sort the channel order in the bouquet.

If no LCNs are present there is nothing for us to sort the list of channels found.

No bouquet will be created if no LCNs are found.

Your provider may have the LCN list not in the standard place or no LCN list at all.

So we can try to locate where the LCN data is we need a 30.40 second recording from each of the 11 frequencies. Please use the tool that we provided a link to.

If you provider does not have LCN data in the SI tables it will be impossible to create an ordered ABM provider. It still may be possible to create a fast scan provider file with channels ordered alphabetically, but that depends what data is available on the 11 transport streams, which is why we need those recordings.

**Comment by robinsmidsrod** [comment] 2019-07-22 20:25
I've managed to capture the transport stream for 562MHz (NRK1 Østfold) using dvbstream, as mentioned in the instructions above. Here is a link to the file: https://www.dropbox.com/s/ague224f6woo0rz/562mhz_nrk1_ostfold.ts?dl=0

If this is correct, do I need to capture more of the frequencies?

Hopefully this is useful to you in finding out more.

**Comment by AbuBaniaz** [comment] 2019-07-22 21:48
Can you obtain all the other frequencies please?

**Comment by robinsmidsrod** [comment] 2019-07-23 07:03
@AbuBaniaz Working on it. Did this one contain anything useful?

**Comment by robinsmidsrod** [comment] 2019-07-23 10:05
@AbuBaniaz @Huevos Okay, here are all the recordings from all the different frequencies, and also the terrestrial.xml file:

https://www.dropbox.com/sh/rec9kcyezk7hh7m/AADHAKxmMRtqjLkznk3ovQfVa?dl=0

Hopefully you're able to get something out of those files. Some of the frequencies had somewhat poor reception, so they might not contain clean information. Hopefully it is enough to find the proper metadata.

It would be helpful if you briefly explain what process you're using to figure out what information is in the files.

**Comment by AbuBaniaz** [comment] 2019-07-23 18:06
>Did this one contain anything useful?

No, that is why we asked for more. Thanks for doing so, we will have a look at it

**Comment by Huevos** [comment] 2019-07-23 22:32
We just look at each transport stream with software that can read the SI tables, e.g. Transedit or DVB Inspector.

**Comment by robinsmidsrod** [comment] 2019-07-24 09:14
@Huevos After installing TransEdit and DVB Inspector I was able to find logical channel lists under PSI -> NIT (using DVB Inspector). It seems like the DVB-T provider is using the NorDig private data serialization format. You can see channel lists using the `Nordig Logical Channel Descriptor V2 (0x87)`. I notice that I can receive both `Østfold (0x3405)` (562mhz_nrk1.ts) and `Buskerud, Tele, Vestfold (0x3403)` (786mhz_nrk_tegnsprak.ts) networks, and they should be different bouquets in the final scan results.

Carefully looking at the channel lists, it seems like channel below LCN 200 are TV, while channels in the 2xx LCN range are radio, and those channels in the 9xx LCN range are TV, but special things like sign-language transmissions and the like.

Here is a screenshot from DVB Inspector showing the LCN for one of the files:

![Screenshot-20190724-103353](https://user-images.githubusercontent.com/92816/61780722-51adf280-ae03-11e9-8c90-c8fca3128974.png)

**Comment by Huevos** [comment] 2019-07-24 18:50
Those tables are pretty severely broken. They say every transport stream is on 794 MHz which obviously is is impossible. We should be able to create a work around for this.

We already have 0x87 in the reader for satellite channels. 
https://github.com/oe-alliance/AutoBouquetsMaker/blob/master/AutoBouquetsMaker/lib/dvbreader.c

We need to check this is compatible with your DVB-T services, but for this we need some debug logs.

Please use the attached file and do an ABM scan with the "extra debug" option switched on.
File goes in: /usr/lib/enigma2/python/Plugins/SystemPlugins/AutoBouquetsMaker/providers

Post the debug logs.

**Comment by robinsmidsrod** [comment] 2019-07-24 20:33
@Huevos I added the file in the folder as mentioned, but I wasn't able to find it in the providers list. Then I noticed after running xmllint on the file that there was an extra double-quote after the word "unknown". Fixing that made the provider show up. Once I did a scan I got some bouquets, but they were all messed up, all four of them.

I got some extra debug info in the logs, but I was unable to figure out where on the filesystem the log file was actually stored, so I had to do the cumbersome method of screenshotting each part of it and adding it below. Would be nice to know where the log file is for any future troubleshooting.

![ABM_log_1](https://user-images.githubusercontent.com/92816/61826480-c7957680-ae62-11e9-8e01-92292213ca2b.jpg)
![ABM_log_2](https://user-images.githubusercontent.com/92816/61826481-c7957680-ae62-11e9-8532-591fa7bfed26.jpg)
![ABM_log_3](https://user-images.githubusercontent.com/92816/61826482-c7957680-ae62-11e9-9c75-ad0ce620f19b.jpg)
![ABM_log_4](https://user-images.githubusercontent.com/92816/61826484-c7957680-ae62-11e9-90b7-5b376bf091d4.jpg)

**Comment by AbuBaniaz** [comment] 2019-07-24 20:39
On OpenATV

Menu > System > log settings
Enable debug logs = yes
You can set the location in that menu. Default is /home/root/logs

You must restart the GUI/Enigma2 for this to take effect. No separate file is written for ABM, its should be added to the system logs

Do you use Skype?

**Comment by robinsmidsrod** [comment] 2019-07-24 21:26
Here is the debug log from the ABM scan:

[Enigma2-debug-20190724_23-12-23.log](https://github.com/oe-alliance/AutoBouquetsMaker/files/3428806/Enigma2-debug-20190724_23-12-23.log)

I have Skype and some other messaging systems (like Telegram). You can find more contact info here: https://robin.smidsrod.no/contact/

**Comment by Huevos** [comment] 2019-07-25 00:16
Don't worry if the bouquets look a mess. There is currently some code missing from Python this provider will need. But looks promising.

[ABM-DvbScanner] NIT content {'logical_channel_number': 1, 'channel_list_name': 'LCN Norway', 'original_network_id': 8770, 'channel_list_id': 13, 'country_code': 'nor', 'service_id': 1005, 'descriptor_tag': 135, 'transport_stream_id': 510, 'visible_service_flag': 1}

This scan was from 562 MHz.

Can you change the frequency in the provider file to "498" MHz and scan again.

This line...
configuration key="unknown"" frequency="562000000">Norway terrestrial</configuration

Also you seem to be missing 2 transport streams. On 562 MHz it shows 5 transport streams, and on 498 it shows 9 transport streams, That gives 13, but your scan only shows 11, maybe due to weak signal.

**Comment by Huevos** [comment] 2019-07-25 00:18
Also, what area/city are we working on?

**Comment by robinsmidsrod** [comment] 2019-07-25 07:54
@Huevos I'm located in the city of Tønsberg in Vestfold county of Norway. My roof antenna is directed against Østfold, so the frequencies broadcasted from that tower are stronger than the ones from "Buskerud, Tele, Vestfold". You are probably correct that some transport streams are missing because of a weak signal.

I'll get back to you with a scan for 498MHz in a little while.

**Comment by robinsmidsrod** [comment] 2019-07-25 08:05
@Huevos Here is the debug log for 498MHz (Buskerud, Tele, Vestfold network). This is from a tower where I know there is a weak signal, so data corruption is highly likely.

[Enigma2-debug-20190725_08-35-59_498mhz.log](https://github.com/oe-alliance/AutoBouquetsMaker/files/3430425/Enigma2-debug-20190725_08-35-59_498mhz.log)

**Comment by robinsmidsrod** [comment] 2019-07-25 08:15
@Huevos Just FYI, the DM7020HD has two tuners. Tuner A is a DVB-S2 tuner connected to Thor satellite at 0.9W (no DISEQ switch) and tuner B is DVB-T connected to old roof antenna with amplifier, directed at Halden signal tower in Østfold.

**Comment by Huevos** [comment] 2019-07-25 09:16
Thanks.

Do you think there is any kind of public document that shows the frequencies on each mast?

We really need to know this because the frequencies listed in the tables are wrong.

**Comment by robinsmidsrod** [comment] 2019-07-25 12:30
@Huevos There is a coverage map available here (in Norwegian): http://ntv.no/sjekk-dekningskart/

It only has traditional UHF/VHF channel numbers, not frequencies. I'll look more to see if I can find a table with details.

**Comment by robinsmidsrod** [comment] 2019-07-25 12:47
@Huevos As mentioned on http://ntv.no/ (a little bit down on the page) it says 

> Norges televisjon AS (NTV) har konsesjon for utbygging og drift av det digitale bakkenettet for TV, og frekvenstillatelse for frekvensspektrumet 470-790 MHz. NTV leverer distribusjonskapasitet til sine kunder NRK og RiksTV, og sørger for stabil utsending av TV- og radiokanaler i det digitale bakkenettet.

It also says (on ntv.no/om-ntv) the following:

> FREKVENSER
> Norges televisjon as har konsesjon for å opprette og drive et digitalt trådløst bakkebasert senderanlegg for kringkasting. Konsesjonen gjelder for bruk i 470-790 MHz-båndet. Frekvensbruken skal være i samsvar med de tekniske spesifikasjonene i Recommendation ITU-R BT.1306 og ITU-R BT1368.

Translated it says that they have permission to use frequencies from 470-790MHz. It should be used in accordance with the ITU-R BT.1306 and ITU-R BT1368 specifications.

This means that they transmit on channels in [Band IV](https://en.wikipedia.org/wiki/Band_IV) and [V](https://en.wikipedia.org/wiki/Band_V), from channel 21 to channel 60.

Hopefully this should be enough to create a complete frequency table.

**Comment by Huevos** [comment] 2019-07-25 13:13
Frequency table is simple. What we need is frequency table that correlates frequency to transport stream ID on each mast.

**Comment by Huevos** [comment] 2019-07-25 13:24
Try the attached file in TerrestrialScan plugin. (Remove ".txt" in file name.)

Goes in: /usr/lib/enigma2/python/Plugins/SystemPlugins/TerrestrialScan.

Send file to receiver by FTP. Restart receiver. Do a scan with TerrestrialScan plugin.

See how the bouquet looks.
[MakeBouquet.py.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/3431716/MakeBouquet.py.txt)

**Comment by robinsmidsrod** [comment] 2019-07-25 13:30
@Huevos I'll try to do that. While I was looking through the files some more, I noticed that the frequency 474MHz was found in the 474mhz_disney_junior.ts file using DVB Inspector. It was under PSI -> NIT -> network 0x3405 -> transport stream 0x213 -> frequency list 0x62. Hopefully this can be used in some way. See attached image.

![DVB-Inspector-474mhz-frequency-found](https://user-images.githubusercontent.com/92816/61878094-a4b1a380-aef0-11e9-8162-1115e3e31eff.png)

**Comment by robinsmidsrod** [comment] 2019-07-25 14:06
@Huevos I've added in the file and scanned using TerrestrialScan. It gives me a bouquet that is mostly correct, but it mixes channels from both the masts that I can receive, so some of the channels have weak signal and some have strong. Is there some way to create multiple bouquets based on the network_id, that way you should be able to get consistent signal strenght?

The channels that don't match against the list on https://www.rikstv.no/produkter/kanalliste/ are the following:

channel 47 is eurosport 1 (list says DR1)
channel 96-99 are swedish (not in list on rikstv.no)
channel 198 is nrk p1 buskerud (not in list)
channel 199 is nrk p1 vestfold (not in list)
channel 995 is nrk3 lydtekst (list says nrk1 lydtekst)
channel 997 is nrk1 lydtekst (list says nrk3 lydtekst)

**Comment by Huevos** [comment] 2019-07-25 16:25
Where the plugin can see 2 transport streams with the same TSID it will automatically select the stronger one. 

Which frequency is Eurosport on? Which frequency is DR1 on? Which frequency are the Swedish channels on?

**Comment by robinsmidsrod** [comment] 2019-07-25 17:49
@Huevos Looking over the details of the generated bouquet, it is a mix of streams from multiple signal towers. If I look at NRK1 and NRK3 they are from different frequencies and different towers. They are also using different TSIDs and frequencies. What I've noticed is that the 86% signal is good, but the 54% is unusable (video/audio is breaking up).

LCN 1 NRK1 Østfold is 562MHz TSID: 0x1fe SNR 86% (25.12dB) (network: Østfold)
LCN 7 NRK3/Super is 786MHz TSID: 0x0136 SNR 54% (15.75dB) (network: Buskerud, Tele, Vestfold)

With regards to the frequencies of those channels you asked about:

LCN 47 (Eurosport 1) is 490MHz TSID: 0x03fd
DR1 is nowhere to be found, maybe stale channel list on website?
LCN 96 (SVT1 Värmland) is 490MHz TSID: 0x03fd
LCN 97 (SVT2 Värmland) is 490MHz TSID: 0x03fd
LCN 98 (SVT Barn/SVT24) is 490MHz TSID: 0x03fd
LCN 99 (Kunskapskanalen) is 490MHz TSID: 0x03fd

From what I can understand those channels above are coming from a Swedish signal tower, considering they have a different TSID/ONID than the other Norwegian channels.

After looking at the information about the two towers within my antenna's reach it seems like each tower is transmitting on 5 distinct frequencies, which covers the entire channel package from NTV. Based on that information it seems reasonable to make one bouquet for each signal tower, as it would ensure the most consistent signal reception depending on the direction of the receiver's antenna.

**Comment by Huevos** [comment] 2019-07-26 00:24
Hard to say without seeing a copy of 490 MHz

**Comment by robinsmidsrod** [comment] 2019-07-26 07:21
@Huevos I've added a dump file for 490MHz in https://www.dropbox.com/sh/rec9kcyezk7hh7m/AADHAKxmMRtqjLkznk3ovQfVa?dl=0 (same as earlier) which does indeed indicate that these 5 channels (plus two more with weak signal) are found by TerrestrialScan. They are indeed Swedish.

**Comment by Huevos** [comment] 2019-07-27 21:20
I don't  think it is realistic trying to create an ABM provider for this situation. The tables are just too broken and to add to the problem you are receiving other mixes from outside Norway.

We should be able to get TerrestrailScan producing a correct bouquet though. I'll post back later with a new version.

**Comment by robinsmidsrod** [comment] 2019-07-28 00:07
@Huevos That's too bad. If you were able to write up exactly what is wrong with the tables and what should be changed for them to be accurate (according to the standard) then I could at least try to send it to NTV and see how they respond. Most likely they'll just ignore us, but it is at least worth a try, just to see how they respond...

Getting some way of getting the standard channel list generated automatically would be a huge improvement, because right now I have to assemble it manually. If you're able to get TV and radio into their separate bouquets that would be really great, and separation according to network_id then I'd be really grateful. Thanks for all the help with tracking this down to the bottom, so far.

**Comment by Huevos** [comment] 2019-07-28 01:33
[plugin.py.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/3438759/plugin.py.txt)

[MakeBouquet.py.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/3438764/MakeBouquet.py.txt)

![1](https://user-images.githubusercontent.com/2067864/62001091-50711400-b0e8-11e9-962d-ccb1fc353243.jpg)

**Comment by robinsmidsrod** [comment] 2019-07-28 16:05
@Huevos Thank you for the files! I've run through a scan now and I do get a useful bouquet out of it with the settings you suggested above. The only problem is that too many of the channels in the bouquet end up coming from the weaker tower, and I have no idea why that is. Maybe my tuner is not able to get the correct signal strength fast enough, so the wrong frequency is used by the bouquet. If it was possible to in some way force the frequencies from one mast to always have priority over another when generating the bouquet I think I would be super happy and things would work out exactly as I need them to. Right now, I'd still need to manually make a bouquet because too many of the channels are unwatchable.

Also, you have a typo in the help message, it is written "Scandinavian".

**Comment by Huevos** [comment] 2019-07-28 16:27
The problem is the signals are not marked in any way which mast they are coming from. 

The plugin waits for signal strength to stabilize before storing it. If this is wrong it is a problem with the signal strength measurement coming from the drivers on your hardware... Or a signal strength algorithm problem in frontend.cpp in the image distro you are using.

OpenViX has a different algorithm but we don't Catch 22.

Most likely is your distro is showing decent signal for both masts even though one is weak.

**Comment by robinsmidsrod** [comment] 2019-07-28 17:24
@Huevos Actually, they are. When you go into PSI->NIT you see the network_id (in DVB Inspector). That number/name you get in there represents the geographical region (or most likely mast) you're receiving.

In DVB Inspector it is listed as table_id_extension, and the one I get the strongest signal from is labeled Østfold (0x3405), which has an ONID of 8770 and a TSID of 510. If you look at the NTV channel to frequency map.txt file in my previously shared Dropbox folder, you can see that both 474MHz and 562MHz both come from Halden, Høyås, which is where my antenna is pointed at (and I have the strongest signal).

If you open up 498Mhz and 578MHz, which are both coming from Frodeåsen, Tele, that is the tower that has the weaker signal. Both of those files have the network_id 0x3403 (Buskerud, Tele, Vestfold) and the ONID 8770 and TSID 335, because they come from the same mast. That is the way you can differentiate them, as far as I can see.

Also, if you open up 490mhz you can see it has a different network_id (0x31a5, Teracom_Mux_1), and a different ONID (8945) and TSID (1021). That is the Swedish tower occasionally receive, but only in good weather. ;)

Are you able to do anything with this information?

**Comment by robinsmidsrod** [comment] 2019-07-28 19:12
@Huevos I've added a PDF to the Dropbox folder with some test specification from RiksTV (NTV) about how to calculate best service selection. I found it somewhere deep in the pages of rikstv.no with some google-fu. From page 23 I think you'll find the juicy bits that'll help you to understand how they expect you to build the service list(s). I specifically talks about what is considered the "same" channel and you should determine which one to use. Hopefully it makes sense. I've added it here for reference.

[riks-tv-test-specification-ver-2.0.pdf](https://github.com/oe-alliance/AutoBouquetsMaker/files/3439495/riks-tv-test-specification-ver-2.0.pdf)

**Comment by robinsmidsrod** [comment] 2019-07-28 20:29
@Huevos I've gone through the bouquet more carefully now, and I've noticed that for all of the NRK TV and radio channels, I've only got one channel (NRK1 Østfold) which is from the mast with the stronger signal (TSID 0x1fe), while all the other channels in the bouquet are from the mast with the weaker signal (TSID 0x136). Is it possible that the channel duplicate selection algorithm is reversed, so it favors the weaker signal instead of the stronger one? Going through the generated bouquet and looking at the signal strength it looks like that to me.

**Comment by Huevos** [comment] 2019-07-29 09:11
No it is not possible the duplication algorithm is reversed.

https://github.com/oe-alliance/oe-alliance-plugins/blob/master/TerrestrialScan/src/TerrestrialScan.py#L416

**Comment by Huevos** [comment] 2019-07-29 21:27
So current logic is... 

Step through frequencies...

For each active transport streams discovered....
Read signal level. 
Read SDT to get TSID + ONID (this can take up to 2 seconds per transport stream)
Where there are duplicate TSID + ONID combinations save the stronger ones.

Once we have a list of transport streams, read the NIT to get the LCNs. Reading the NIT can take up to 30 seconds per transport stream.

To read the Network ID would require reading the NIT on every transport stream before saving.

**Comment by robinsmidsrod** [comment] 2019-07-30 07:54
@Huevos As far as I can tell from the rikstv-test-specification file I uploaded earlier (page 23) it says the following:

> Due to the asymmetrical nature of the terrestrial network and the fact that one unique
service can be receive from different transmitters (and frequencies), independent of the
regions, the following rules shall apply when building the service lists:
> 1. A unique service shall only be listed once. Observe that a unique service is
defined by its _original_network_id_ and _service_id_ in the terrestrial network
(not _transport_stream_id_)
> 2. If the same unique service is found on several frequencies, the frequency
with the best reception shall be used for that particular service. The IRD
shall use the Signal Strength Indicator (SSI) and Signal Quality Indicator
(SQI) as defined by Nordig Unified Specification [2] when determining the
best frequency to use for a service. The Nordig Unified Specification [2]
includes an appendix with implementation guidelines for selecting
frequency in non-trivial situations.

Is this in line with what you described in the previous comment?

Also, is it possible that 2 seconds is not enough to get a stable signal level to store with the TSID/ONID from SDT? My STB is quite old, so it might actually take more than 2 seconds to get the correct signal level. Could this 2 second timeout be set by the user to work around slow hardware? I've noticed that zapping to a DVB-T channel can sometimes take up to 6 seconds on my hardware.

**Comment by Huevos** [comment] 2019-07-30 15:14
First, lets be clear before we move on. ONID (Original Network ID) and Network ID are very different things. ONID for the current transponder can be retrieved from "SDT Actual", Network ID cannot and must be retrieved from the NIT.

The plugin says "Network ID" in the config page, but should say "Original Network ID". This needs changing.

The 2 seconds is is part of the DVB standard, which says the "SDT Actual" is to have a repeat interval of at least once every 2 seconds. This is not imposed by the plugin. Intead there is a 5 second timeout. 
https://github.com/oe-alliance/oe-alliance-plugins/blob/master/TerrestrialScan/src/TerrestrialScan.py#L377

To allow the signal strength to stabilize there is a 2 second sleep period imposed by the plugin. You can try changing this and see if your hardware responds favorably.
https://github.com/oe-alliance/oe-alliance-plugins/blob/master/TerrestrialScan/src/TerrestrialScan.py#L410

In your quote "point 1" is not compatible with the DVB standard. The DVB standard says that a SID is unique within a TSID and a TSID is unique within the ONID. Accord to your provider the unique combination is "ONID + SID". This plugin has no interest in SIDs because the DVB standard says the unique combination for a transport stream is "ONID + TSID".

I suspect the above is where we are failing. In all other systems so far encountered, if a unique transport stream is available on different masts the TSID will be identical (DVB standard). So we just need to test "ONID + TSID + Signal Quality" to identify unique transport streams. In fact if it is a repeater it must be identical because it is just resending the signal from the primary mast on a different frequency.

So if we are going to make any progress we need would need to completely rewrite the plugin contrary to DVB standards.

**Comment by robinsmidsrod** [comment] 2019-07-30 19:58
@Huevos That "point 1" that I'm referencing is directly from the RiksTV/NTV specification for STBs that are approved to work with Norwegian DVB-T transmissions. Why am I not surprised that they're violating the DVB standard? It is so typical, in Norwegian technical standards, that they deviate from the international standards... *sigh* It isn't the first time I've heard about this happening.

I've run a new scan now with the sleep() changed from 2 to 5 seconds. It helped a lot! Now all of the NRK channels (TV and radio) in the bouquet are coming from the 0x1fe TSID, which is the one with the stronger signal. Is it possible to make the sleep() configurable, or should we just increase it to take into account slower hardware?

**Comment by robinsmidsrod** [comment] 2019-07-30 20:10
@Huevos Also, the final gesture that would make this really nice is if the radio channels could be added to a Radio "Terrestrial" bouquet instead of the TV "Terrestrial" bouquet.

Looking at the information in the PSI->SDT it does seem like the TV channels use service_type 0x19 (25, H264/AVC HD digital television service) and the radio channels use service_type 0xA (10, advanced codec digital radio sound service), so it seems doable to separate them into different bouquets.

**Comment by Huevos** [comment] 2019-07-30 23:28
[plugin.py.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/3449172/plugin.py.txt)
[MakeBouquet.py.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/3449174/MakeBouquet.py.txt)
[TerrestrialScan.py.txt](https://github.com/oe-alliance/AutoBouquetsMaker/files/3449175/TerrestrialScan.py.txt)

That adds the stabilization time to the user interface. I don't have time to code a radio bouquet at this time. Is there a collision between the TV and radio LCNs?

**Comment by robinsmidsrod** [comment] 2019-07-31 07:00
@Huevos Thanks a bunch! I'll try them out a bit later today.

I was just wondering - since you don't have time to create a separate radio bouquet, would it be possible to fill in the DESCRIPTION line in the bouquet file with the channel name, as it would make it much easier when I copy the relevant lines into a new (manually created) radio bouquet file.

Also, when do you expect these changes you've made to TerrestrialScan to make it into OpenATV and/or the plugin there? Just wondering how long I'll need to hang on to these custom tweaks you've made.

**Comment by Huevos** [comment] 2019-07-31 10:00
I can push these changes to github later today if I have a minute. That would get them into OpenATV at the next build.

Is there a collision between tv and radio LCNs?

**Comment by robinsmidsrod** [comment] 2019-07-31 12:15
@Huevos As far as I can tell, there are no collisions between radio and TV LCNs. For Norwegian DVB-T signals the radio LCNs are all 2xx. There are no TV channels in that range. TV channels are all below 100 or 9xx.

I noticed you had some more typos in your files. In American English, it is written "Stabilization", or in UK English "Stablisation". With or without Z depending on language dialect. Not sure which language dialect is normally used, but you should continue using the same as the rest. There were also some other typos surrounding the same word in different forms.

Great work all together!

Based on everything we've figured out so far, is an ABM provider still out of the question?

**Comment by Huevos** [comment] 2019-07-31 15:02
TerrestrialScan reads every transport stream (UHF, 8 MHz steps). That means it doesn't matter if the frequency data is wrong in the NIT, because we can work it out from the tuned frequency.

ABM works by reading one single transport stream and harvests all the frequency data and other data to required to create the bouquets from that one single transponder.

To make an ABM provider we would need to know the home transponder frequency for every mast in the country, and for the frequency data not to be broken how it is in the SI tables.

Also, we would need to add code to handle "channel_list_id" for DVB-T providers. And to know the correct "channel_list_id" of every mast in the country.

Given that it is unlikely we could get the provider to fix the frequency data in their SI tables and that there is no known public source for the home transponders or "channel_list_id" of every mast in the country, there is little hope of an ABM bouquet to be created for this provider.

**Comment by Huevos** [comment] 2019-07-31 15:52
https://github.com/oe-alliance/oe-alliance-plugins/commit/2619b7cf0a094b294cbc6ea9b5de8eef29b2d0bf

**Comment by robinsmidsrod** [comment] 2019-08-02 12:27
@Huevos Thank you for the updated plugin. I've installed it and run a scan with the new code.

I also noticed something new. I found a website with documents related to Norwegian frequency usage in the 470-790MHz bands:

https://frekvens.nkom.no/#/main

I'm not sure if it actually has a frequency chart, as there are a lot of documents in the list.

**Comment by Huevos** [comment] 2019-08-02 16:47
You don't need a frequency chart. We know it is 8 MHz steps. What you need is a list of home transponders and channel_list_id 's, and that the tables are not broken. Right now NIT shows incorrect frequency data. ABM uses that data.

**Comment by robinsmidsrod** [comment] 2019-08-02 21:21
@Huevos I gave you the link because it contains a lot of documentation, not necessarily only frequency information. The problem is that there is so much documentation that I don't know which document _might_ contain the information we need.

**Comment by Huevos** [comment] 2020-03-12 21:00
Closing this. TerrestrialScan can be used as a substitute for ABM in this situation.

**Closed by Huevos** 2020-03-12 21:00 UTC
